name: TaskLab CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew test

  detekt:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Detekt
        run: ./gradlew detekt

  debug-build:
    needs: [ unit-tests, detekt ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload build file
        uses: actions/upload-artifact@v3
        with:
          name: TaskLab_Debug
          path: app/build/outputs/apk/debug/app-debug.apk

  distribution:
    if: github.event_name != 'pull_request'
    needs: [ debug-build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: TaskLab_Debug

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_DEBUG }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Stakeholders
          file: app-debug.apk
