## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

## 2
jobs:
  ## 3
  Tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew test

  Build:
    needs: [ Tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Expose version name
          id: versionReader
          uses: michpohl/android-expose-version-name-action@v1.0.0
          with:
            expose-version-name: 'true'
            expose-version-code: 'true'
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.1"
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: CarBox_Release_${{ steps.versionReader.env.ANDROID_VERSION_NAME }}.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

  Distribute:
    # 1
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      # 2
      - uses: actions/download-artifact@master
        with:
          name: CarBox_Release_${{ steps.versionReader.env.ANDROID_VERSION_NAME }}.apk
      #3
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Stakeholders
          file: app-release-unsigned-signed.apk
