## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

## 2
jobs:
  ## 3
  Unit_Tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew test

  Android_Tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew connectedAndroidTest

  Build:
    needs: [ Unit_Tests, Android_Tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v3
      # 2
      - name: Version reader
        id: versionReader
        uses: Devofure/version-reader-action@v1.1.0
        with:
          gradlePath: app/build.gradle
      # 3
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 4
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.1"
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: CarBox_Release_v${{ steps.versionReader.outputs.cleanVersionName }}(${{ steps.versionReader.outputs.versionCode }}).apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
      # 6
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

  Distribute:
    # 1
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v3
      # 2
      - name: version reader
        id: versionReader
        uses: Devofure/version-reader-action@v1.1.0
        with:
          gradlePath: app/build.gradle # Default is app/build.gradle
      # 3
      - uses: actions/download-artifact@master
        with:
          name: CarBox_Release_v${{ steps.versionReader.outputs.cleanVersionName }}(${{ steps.versionReader.outputs.versionCode }}).apk
      # 4
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Stakeholders
          file: app-release-unsigned-signed.apk
