name: Test and deploy

on:
#  push:
#    tags:
#      - 'v*'
#    branches:
#      - main
#      - release
#  pull_request:
#    branches:
#      - main
#      - release

jobs:
  Tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew testRelease

  Build:
    needs: [ Tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v3
      # 2
      - name: Generate Release APK
        run: ./gradlew --no-daemon assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.1"
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

  Distribute:
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/download-artifact@master
        with:
          name: release.apk
      # 2
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Stakeholders
          file: app-release-unsigned-signed.apk
